// <auto-generated />
using System;
using GameForum.EFDataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GameForum.EFDataAccess.Migrations
{
    [DbContext(typeof(GameForumDbContext))]
    partial class GameForumDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GameForum.ApplicationLogic.Model.Comment", b =>
                {
                    b.Property<Guid>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatorIDID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GameID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommentID");

                    b.HasIndex("CreatorIDID");

                    b.HasIndex("GameID");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("GameForum.ApplicationLogic.Model.Game", b =>
                {
                    b.Property<Guid>("GameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatorIDID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DateCreated")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NOComments")
                        .HasColumnType("int");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameID");

                    b.HasIndex("CreatorIDID");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GameForum.ApplicationLogic.Model.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GameForum.ApplicationLogic.Model.Comment", b =>
                {
                    b.HasOne("GameForum.ApplicationLogic.Model.User", "CreatorID")
                        .WithMany()
                        .HasForeignKey("CreatorIDID");

                    b.HasOne("GameForum.ApplicationLogic.Model.Game", "GameId")
                        .WithMany()
                        .HasForeignKey("GameID");
                });

            modelBuilder.Entity("GameForum.ApplicationLogic.Model.Game", b =>
                {
                    b.HasOne("GameForum.ApplicationLogic.Model.User", "CreatorID")
                        .WithMany()
                        .HasForeignKey("CreatorIDID");
                });
#pragma warning restore 612, 618
        }
    }
}
